name: Maven Release
on:
  push:
    tags:
      - 'v*'
permissions:
    contents: write
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Find the JAR file
        id: find_jar
        shell: bash
        run: |
          JAR_FILE=$(find target -name "*.jar" -not -name "*javadoc.jar" -not -name "*sources.jar" | head -n 1)
          echo "Found JAR file: $JAR_FILE"
          echo "path=$JAR_FILE" >> $GITHUB_OUTPUT
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_jar.outputs.path }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
